name: Run Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xorg-dev xvfb libgl1-mesa-dev libglfw3-dev libfreetype6-dev

    - name: Pre-download Go modules
      run: |
        go mod download

    - name: Start Xvfb
      run: |
        /usr/bin/Xvfb :99 -screen 0 3000x3000x24 &
        export DISPLAY=:99

    - name: Run tests
      run: |
        cd _test
        ./run_tests.sh
      env:
        DISPLAY: :99
        
